/*
 * Copyright (c) 2026 GitLive Ltd.  Use of this source code is governed by the Apache 2.0 license.
 */

package com.google.firebase.messaging

import com.google.android.gms.tasks.Task

/**
 * Firebase Cloud Messaging, as the Android SDK's `com.google.firebase.messaging.FirebaseMessaging`. Receiving messages
 * is platform code on every platform (`FirebaseMessagingService` on Android).
 *
 * The JS SDK has no topic subscription (a web client's token is subscribed from a server with the Admin SDK) and no
 * auto-init (a token is only ever generated by [getToken]): those members do nothing on JS and carry
 * `@UnsupportedOnJs`, so code compiled for JS gets a warning until it opts in.
 */
public expect class FirebaseMessaging {
    /** Deletes the registration token of this app instance, so it stops receiving messages. */
    public fun deleteToken(): Task<Nothing?>

    /** The registration token of this app instance, requested from the backend if needed. */
    public fun getToken(): Task<String>

    /** Subscribes this app instance to [topic]. A no-op on JS, whose SDK has no client-side topic subscription. */
    public fun subscribeToTopic(topic: String): Task<Nothing?>

    /** Unsubscribes this app instance from [topic]. A no-op on JS, whose SDK has no client-side topic subscription. */
    public fun unsubscribeFromTopic(topic: String): Task<Nothing?>

    /**
     * Whether the registration token is generated automatically at startup, which apps turn off until the user has
     * consented. Always false on JS, where a token is only generated by [getToken]; setting it does nothing there.
     */
    public var isAutoInitEnabled: Boolean

    public companion object {
        /** The scope of the registration token, `FCM`; a remnant of the Instance ID API. */
        @Deprecated("The registration token has no scope any more; getToken() returns the FCM token")
        public val INSTANCE_ID_SCOPE: String

        /** The [FirebaseMessaging] singleton. */
        public fun getInstance(): FirebaseMessaging
    }
}
