name: 'Setup Tests'
description: 'Prepares to run tests on Firebase emulator'

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: gradle
    - name: Gradle cache
      uses: gradle/gradle-build-action@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Install Firebase tools
      run: npm install -g firebase-tools
    - name: Start Firebase emulator
      run: "firebase emulators:start --config=./test/firebase.json &"