name: JVM

on:
  push:
    branches: [ jvm-target ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: assemble
      env:
        TOKEN: ${{ secrets.AUTO_TOKEN }}
        USERNAME: ${{ secrets.AUTO_USERNAME }}
    - name: Publish maven jvm
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: :firebase-app:publishJvmPublicationToGitHubPackagesRepository :firebase-auth:publishJvmPublicationToGitHubPackagesRepository :firebase-common:publishJvmPublicationToGitHubPackagesRepository :firebase-database:publishJvmPublicationToGitHubPackagesRepository :firebase-firestore:publishJvmPublicationToGitHubPackagesRepository :firebase-functions:publishJvmPublicationToGitHubPackagesRepository
      continue-on-error: true
      env:
        TOKEN: ${{ secrets.AUTO_TOKEN }}
        USERNAME: ${{ secrets.AUTO_USERNAME }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}
    - name: Publish maven js
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: :firebase-app:publishJsPublicationToGitHubPackagesRepository :firebase-auth:publishJsPublicationToGitHubPackagesRepository :firebase-common:publishJsPublicationToGitHubPackagesRepository :firebase-database:publishJsPublicationToGitHubPackagesRepository :firebase-firestore:publishJsPublicationToGitHubPackagesRepository :firebase-functions:publishJsPublicationToGitHubPackagesRepository
      continue-on-error: true
      env:
        TOKEN: ${{ secrets.AUTO_TOKEN }}
        USERNAME: ${{ secrets.AUTO_USERNAME }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}
    - name: Setup NPM
      run: npm config set //npm.pkg.github.com/:_authToken=$token
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish npm
      uses: eskatos/gradle-command-action@v1
      continue-on-error: true
      with:
        arguments: prepareForNpmPublish publishToNpm
