name: JVM

on:
#  push:
#    branches: [ jvm-target ]
  pull_request:
    branches: [ jvm-target ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      uses: eskatos/gradle-command-action@v1
      with:
#        arguments: build publishJvmPublicationToGitHubPackagesRepository publishJsPublicationToGitHubPackagesRepository prepareForNpmPublish
        arguments: build prepareForNpmPublish
      env:
        TOKEN: ${{ secrets.AUTO_TOKEN }}
        USERNAME: ${{ secrets.AUTO_USERNAME }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}
    - uses: JS-DevTools/npm-publish@v1
      with:
        registry: https://npm.pkg.github.com
        package: build/node_module/package.json
        token: ${{ secrets.GITHUB_TOKEN }}
