name: Lint and API Checks

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ci-lint-api-check-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lintAndApiChecks:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle
      - name: Cocoapods cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cocoapods
            ~/Library/Caches/CocoaPods
            */build/cocoapods
            */build/classes
          key: cocoapods-cache-v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      - name: Format Kotlin
        run: ./gradlew formatKotlin
      - name: Api File Update
        run: ./gradlew apiDump
      - run: git status
      - uses: stefanzweifel/git-auto-commit-action@v6
