name: Pull Request Target

on:
  pull_request_target:
    branches: [ master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lintAndApiChecks:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Format Kotlin
        run: ./gradlew formatKotlin
      - name: Api File Update
        run: ./gradlew apiDump
      - uses: stefanzweifel/git-auto-commit-action@v6
