name: Push

on: [ push ]

jobs:
  formatKotlin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Format Kotlin
        run: ./gradlew formatKotlin
      - name: Api File Update
        run: ./gradlew apiDump
      - uses: stefanzweifel/git-auto-commit-action@v6
      - name: lintKotlin
        run: ./gradlew lintKotlin
      - name: Api Check
        run: ./gradlew apiCheck
